package com.dao;

import com.ody.p2p.entity.ScanHistoryEntity;
import com.ody.p2p.entity.SearchRiCiEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scanHistoryEntityDaoConfig;
    private final DaoConfig searchRiCiEntityDaoConfig;

    private final ScanHistoryEntityDao scanHistoryEntityDao;
    private final SearchRiCiEntityDao searchRiCiEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scanHistoryEntityDaoConfig = daoConfigMap.get(ScanHistoryEntityDao.class).clone();
        scanHistoryEntityDaoConfig.initIdentityScope(type);

        searchRiCiEntityDaoConfig = daoConfigMap.get(SearchRiCiEntityDao.class).clone();
        searchRiCiEntityDaoConfig.initIdentityScope(type);

        scanHistoryEntityDao = new ScanHistoryEntityDao(scanHistoryEntityDaoConfig, this);
        searchRiCiEntityDao = new SearchRiCiEntityDao(searchRiCiEntityDaoConfig, this);

        registerDao(ScanHistoryEntity.class, scanHistoryEntityDao);
        registerDao(SearchRiCiEntity.class, searchRiCiEntityDao);
    }
    
    public void clear() {
        scanHistoryEntityDaoConfig.clearIdentityScope();
        searchRiCiEntityDaoConfig.clearIdentityScope();
    }

    public ScanHistoryEntityDao getScanHistoryEntityDao() {
        return scanHistoryEntityDao;
    }

    public SearchRiCiEntityDao getSearchRiCiEntityDao() {
        return searchRiCiEntityDao;
    }

}
