package com.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.ody.p2p.entity.SearchRiCiEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SEARCH_RI_CI_ENTITY".
*/
public class SearchRiCiEntityDao extends AbstractDao<SearchRiCiEntity, Long> {

    public static final String TABLENAME = "SEARCH_RI_CI_ENTITY";

    /**
     * Properties of entity SearchRiCiEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property RiCiName = new Property(1, String.class, "riCiName", false, "RI_CI_NAME");
    }


    public SearchRiCiEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SearchRiCiEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_RI_CI_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"RI_CI_NAME\" TEXT);"); // 1: riCiName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_RI_CI_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchRiCiEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String riCiName = entity.getRiCiName();
        if (riCiName != null) {
            stmt.bindString(2, riCiName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchRiCiEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String riCiName = entity.getRiCiName();
        if (riCiName != null) {
            stmt.bindString(2, riCiName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SearchRiCiEntity readEntity(Cursor cursor, int offset) {
        SearchRiCiEntity entity = new SearchRiCiEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // riCiName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchRiCiEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRiCiName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SearchRiCiEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SearchRiCiEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchRiCiEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
